version: "3.2"

services:
  nlp-engine:
    image: sflorenz05/lambda-engine:v1
    container_name: lambda-engine
    hostname: lambda-engine
    working_dir: /administrator
    volumes:
      - ./../../lambda-engine:/administrator
    command: sh -c "python3 app.py"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      REGION_NAME: "${REGION_NAME}"
      PATH_INPUT: "${PATH_INPUT}"
    ports:
      - 5000:5000
