version: "3.2"

services:
  nlp-engine:
    image: nlp-engine
    container_name: nlp-engine
    hostname: nlp-engine
    working_dir: /administrator
    volumes:
      - ./../nlp-engine/data/input:/administrator/input
      - ./../nlp-engine/data/output:/administrator/output
      - ./../nlp-engine/library/src/library:/administrator/library
      - ./../nlp-engine/app.py:/administrator/app.py
    command: sh -c "python3 -m flask run --host=0.0.0.0"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      REGION_NAME: "${REGION_NAME}"
    ports:
      - 5000:5000
